r/aws_bedrockagent_custom_model(test): prefer `nova` foundation models
```console
% make t K=bedrock T=TestAccBedrock_serial/CustomModel
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running acceptance tests on branch: 🌿 td-bedrock-nova 🌿...
TF_ACC=1 go1.26.2 test ./internal/service/bedrock/... -v -count 1 -parallel 20 -run='TestAccBedrock_serial/CustomModel'  -timeout 360m -vet=off
2026/05/07 13:10:26 Creating Terraform AWS Provider (SDKv2-style)...
2026/05/07 13:10:26 Initializing Terraform AWS Provider (SDKv2-style)...

--- FAIL: TestAccBedrock_serial (10681.47s)
    --- FAIL: TestAccBedrock_serial/CustomModel (10681.47s)
        --- PASS: TestAccBedrock_serial/CustomModel/disappears (75.04s)
        --- FAIL: TestAccBedrock_serial/CustomModel/tags (1246.57s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_updateToResourceOnly (67.01s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_emptyResourceTag (36.03s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/AddOnUpdate (64.51s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/EmptyTag_OnCreate (56.20s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/EmptyTag_OnUpdate_Add (59.40s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_providerOnly (119.61s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/ComputedTag_OnCreate (64.77s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_overlapping (115.89s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/ComputedTag_OnUpdate_Add (67.25s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/ComputedTag_OnUpdate_Replace (51.39s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/IgnoreTags_Overlap_DefaultTag (62.55s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/IgnoreTags_Overlap_ResourceTag (56.74s)
            --- FAIL: TestAccBedrock_serial/CustomModel/tags/basic (17.65s)
            --- FAIL: TestAccBedrock_serial/CustomModel/tags/EmptyMap (17.59s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/EmptyTag_OnUpdate_Replace (43.91s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_nonOverlapping (104.10s)
            --- FAIL: TestAccBedrock_serial/CustomModel/tags/DefaultTags_updateToProviderOnly (65.03s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_nullOverlappingResourceTag (52.17s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/DefaultTags_nullNonOverlappingResourceTag (62.73s)
            --- PASS: TestAccBedrock_serial/CustomModel/tags/null (62.03s)
        --- PASS: TestAccBedrock_serial/CustomModel/validationDataConfig (60.22s)
        --- FAIL: TestAccBedrock_serial/CustomModel/validationDataConfigWaitForCompletion (2271.82s)
        --- FAIL: TestAccBedrock_serial/CustomModel/pluralDataSourceBasic (4487.25s)
        --- PASS: TestAccBedrock_serial/CustomModel/basic (79.69s)
        --- FAIL: TestAccBedrock_serial/CustomModel/kmsKey (17.40s)
        --- FAIL: TestAccBedrock_serial/CustomModel/vpcConfig (15.71s)
        --- FAIL: TestAccBedrock_serial/CustomModel/singularDataSourceBasic (2206.14s)
        --- FAIL: TestAccBedrock_serial/CustomModel/Identity (221.62s)
            --- PASS: TestAccBedrock_serial/CustomModel/Identity/ExistingResourceNoRefresh (102.78s)
            --- FAIL: TestAccBedrock_serial/CustomModel/Identity/basic (14.31s)
            --- PASS: TestAccBedrock_serial/CustomModel/Identity/ExistingResource (104.53s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/bedrock    10688.766s
```

Previously tests were not executing at all due to the use of a
deprecated foundation model. Additional fixes for the still failing
tests will be applied in a later change.